language: python

python:
  - "3.6"
  - "2.7"

env:
  R_LIBS=$HOME/R_libs/

cache:
  directories:
    - $HOME/R_libs
    - $HOME/.cache/pip

before_install:
  - sudo apt-get install -y bedtools
  - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty-cran35/" >> /etc/apt/sources.list'
  - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
  - gpg -a --export E084DAB9 | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install r-base
  - R -e "if (!requireNamespace('BiocManager', quietly = TRUE)){install.packages('BiocManager', repos='https://CRAN.R-project.org')}; BiocManager::install(c('DESeq2', 'preprocessCore', 'cqn'), version = '3.8')"
  # The following is just required to have a working DISPLAY variable in Travis and for Python2 only for some reason
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - pip install -r requirements/requirements.test.txt
  - pip install .[r]

script:
  - pytest --disable-warnings --show-capture=no --cov ngs_toolkit --cov-report term --cov-report xml test/test_*.py

after_success:
  - codecov -f coverage.xml
  - python-codacy-coverage -r coverage.xml
