language: python
os: linux
dist: bionic

python:
  - "3.6"
  - "3.7"

env:
  R_LIBS=$HOME/R_libs/

cache:
  directories:
    - $HOME/R_libs
    - $HOME/.cache/pip

services:
  - xvfb

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
  - wget http://ftp.br.debian.org/debian/pool/main/b/bedtools/bedtools_2.27.1+dfsg-4_amd64.deb
  - sudo dpkg -i bedtools_2.27.1+dfsg-4_amd64.deb
  - sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
  - sudo apt-get update
  - sudo apt-get -y install r-base r-base-core r-recommended gfortran liblapack-dev libopenblas-dev
  - R -e "install.packages('BiocManager', repos='https://CRAN.R-project.org')"
  - R -e "library('BiocManager'); BiocManager::install(c('DESeq2', 'preprocessCore', 'cqn'), version = '3.9')"
  - pip install git+https://github.com/afrendeiro/combat.git

before_script:
  - export DISPLAY=:99.0

install:
  - pip install .[testing]

script:
  - pytest --disable-warnings --show-capture=no --cov ./ --cov-report term --cov-report xml --pyargs ngs_toolkit


after_success:
  - coverage xml
  - codecov -f coverage.xml
  - python-codacy-coverage -r coverage.xml
