language: python
os: linux
dist: bionic

python:
  - "3.6"
  - "3.7"

cache:
  directories:
    - $HOME/.cache/pip

services:
  - xvfb

before_install:
  # Install bedtools
  - sudo apt-get -y install bedtools
  # Install R
  - sudo apt-get -y install r-base
  # Add bioconductor libraries
  - sudo apt-get -y install r-bioc-deseq2 r-bioc-preprocesscore
  # Install Combat
  - pip install git+https://github.com/afrendeiro/combat.git

install:
  - pip install .[testing]

before_script:
  - export DISPLAY=:99.0
  - R -e "suppressMessages(library("DESeq2")); suppressMessages(library("preprocessCore")); sessionInfo()"

script:
  # - pytest ngs_toolkit/tests/test_plot_differential.py
  - pytest --disable-warnings --show-capture=no --cov ./ --cov-report term --cov-report xml --pyargs ngs_toolkit
  

after_success:
  # - ls
  - coverage xml
  - codecov -f coverage.xml
  - python-codacy-coverage -r coverage.xml
