language: python

python:
  - "3.5"
  - "3.6"

env:
  R_LIBS=$HOME/R_libs/

cache:
  directories:
    - $HOME/R_libs
    - $HOME/.cache/pip

services:
  - xvfb

before_install:
  - wget http://ftp.debian.org/debian/pool/main/b/bedtools/bedtools_2.21.0-1_amd64.deb
  - sudo dpkg -i bedtools_2.21.0-1_amd64.deb
  - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty-cran35/" >> /etc/apt/sources.list'
  - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
  - gpg -a --export E084DAB9 | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install r-base gfortran --allow-unauthenticated
  - sudo apt-get -y install liblapack-dev libopenblas-dev 
  - R -e "if (!requireNamespace('BiocManager', quietly = TRUE)){install.packages('BiocManager', repos='https://CRAN.R-project.org')}; BiocManager::install(c('DESeq2', 'preprocessCore', 'cqn'), version = '3.9')"

before_script:
  - export DISPLAY=:99.0

install:
  - pip install git+https://github.com/afrendeiro/combat.git
  - pip install -r requirements/requirements.test.txt
  - pip install .[rstats]

script:
  - pytest --disable-warnings --show-capture=no --cov ./ --cov-report term --cov-report xml tests/test_*.py

after_success:
  - coverage xml
  - codecov -f coverage.xml
  - python-codacy-coverage -r coverage.xml
